In [9]:
import cv2
import numpy as np
from PIL import Image

In [10]:
# input_path = input("Enter with the input path: ")
# output_path = input("Enter with the output path: ")
input_path = '../images/bitmap.pbm'
output_path = '../outputs'

In [11]:
img = cv2.imread(input_path, 0)
img = cv2.bitwise_not(img)
print(len(img))
print(len(img[0]))

1374
2233


In [12]:
kernel_1 = np.ones((1,100), np.uint8)
dilation_1 = cv2.dilate(img, kernel_1, iterations = 1)
erosion_1 = cv2.erode(dilation_1, kernel_1, iterations = 1)

In [13]:
kernel_2 = np.ones((200,1), np.uint8)
dilation_2 = cv2.dilate(img, kernel_2, iterations = 1)
erosion_2 = cv2.erode(dilation_2, kernel_2, iterations = 1)

In [14]:
intersection = cv2.bitwise_and(erosion_1, erosion_2)

In [15]:
kernel_3 = np.ones((1,30), np.uint8)
closing = cv2.morphologyEx(intersection, cv2.MORPH_CLOSE, kernel_3)

In [16]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(closing, 4, cv2.CV_32S)
background = stats[0]
print(num_labels)
print(labels)
print(len(stats))
print(len(stats[0]))
print(stats)
print(len(centroids))
print(len(centroids[0]))
print(centroids)

54
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
54
5
[[      0       0    2233    1374 2177519]
 [   1039      28    1150      25   24201]
 [     32      36      42      21     866]
 [   1343     131       2       3       4]
 [    264     139     572     561  315070]
 [   1142     147    1046      40   26026]
 [   1142     198    1046      40   27655]
 [   1142     248     636      39   16418]
 [   1182     298    1007      39   27082]
 [   1142     348    1047      40   24980]
 [   1205     350       4       5      18]
 [   1144     399    1045      38   23916]
 [   2169     398       4       5      17]
 [   1143     448    1046      40   27645]
 [   1144     499    1046      40   25112]
 [   1146     548    1044      40   27850]
 [   1144     599    1046      39   25728]
 [   1144     649    1046      39   29589]
 [   1145     700     435      31   10046]
 [    478     734      12      20     122]
 [   1411   